# Generated by Django 6.0 on 2026-02-27 19:01

import rentit.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', rentit.models.UserManager()),
            ],
        ),
    ]
