# Generated by Django 6.0 on 2026-02-27 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentit', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='first_last_not_empty',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='uniq_first_last_case_insensitive',
        ),
    ]
