# Generated by Django 6.0 on 2026-02-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentit', '0003_alter_user_options_remove_user_first_last_not_empty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='Kathmandu', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default='Nepal', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='Kathmandu', max_length=10),
            preserve_default=False,
        ),
    ]
