# Generated by Django 6.0 on 2026-02-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentit', '0004_remove_user_address_alter_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
