# Generated by Django 6.0 on 2026-02-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentit', '0006_alter_listing_options_alter_listingimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
