# Generated by Django 6.0 on 2026-02-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentit', '0007_systemlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='apt_suite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='barbecue_grill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='bath_tub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='beds',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default='All', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='cooking_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='country',
            field=models.CharField(default='Nepal', max_length=120),
        ),
        migrations.AddField(
            model_name='listing',
            name='dedicated_workspace',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='dryer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='fire_extinguisher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='first_aid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='hangers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='iron',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='microwave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='outdoor_shower',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='personal_care',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='province',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='refrigerator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='security_cameras',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='stove',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='tv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='washer',
            field=models.BooleanField(default=False),
        ),
    ]
