# Generated by Django 6.0 on 2026-03-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentit', '0008_booking_host_rejection_reasons_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.AddField(
            model_name='booking',
            name='esewa_ref_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='esewa_transaction_uuid',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('khalti', 'Khalti'), ('esewa', 'eSewa'), ('cash', 'Cash')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
