# Generated by Django 6.0 on 2026-02-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentit', '0008_listing_apt_suite_listing_barbecue_grill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('room', 'Room'), ('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('shared_room', 'Shared Room')], default='room', max_length=20),
        ),
    ]
