# Generated by Django 6.0 on 2026-03-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentit', '0009_alter_booking_options_booking_esewa_ref_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('khalti', 'Khalti'), ('esewa', 'eSewa'), ('cash_in_hand', 'Cash in Hand')], max_length=20, null=True),
        ),
    ]
