# Generated by Django 6.0 on 2026-02-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentit', '0009_alter_listing_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='camp_fire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='free_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='garden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='highlight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='highlight_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='outdoor_dining_area',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='pet_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='private_patio_or_balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='self_check_in',
            field=models.BooleanField(default=False),
        ),
    ]
