# Generated by Django 6.0 on 2026-02-10 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentit', '0010_listing_camp_fire_listing_free_parking_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemLog',
        ),
    ]
