# Generated by Django 6.0 on 2026-02-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentit', '0011_delete_systemlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='region',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
