# Generated by Django 6.0 on 2026-04-03 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentit', '0011_platformsetting_booking_host_payout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostapplication',
            name='business_registration',
        ),
        migrations.RemoveField(
            model_name='hostapplication',
            name='citizenship_image',
        ),
        migrations.RemoveField(
            model_name='hostapplication',
            name='tax_number',
        ),
        migrations.AddField(
            model_name='hostapplication',
            name='agreed_to_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostapplication',
            name='bank_verified_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostapplication',
            name='citizenship_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='host_verification/citizenship/'),
        ),
        migrations.AddField(
            model_name='hostapplication',
            name='identity_verified_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostapplication',
            name='ownership_document',
            field=models.FileField(blank=True, null=True, upload_to='host_verification/property_docs/'),
        ),
        migrations.AddField(
            model_name='hostapplication',
            name='pan_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='host_verification/business_docs/'),
        ),
        migrations.AddField(
            model_name='hostapplication',
            name='permanent_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostapplication',
            name='phone_verified_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostapplication',
            name='property_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostapplication',
            name='property_verified_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostapplication',
            name='selfie_with_id',
            field=models.ImageField(blank=True, null=True, upload_to='host_verification/selfie/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='hostapplication',
            name='citizenship_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hostapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_host_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hostapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('needs_more_info', 'Needs More Info'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='host_application_status',
            field=models.CharField(choices=[('none', 'No Application'), ('pending', 'Pending Review'), ('needs_more_info', 'Needs More Info'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
    ]
