# Generated by Django 6.0 on 2026-04-05 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentit', '0012_remove_hostapplication_business_registration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('host_application_submitted', 'Host Application Submitted'), ('host_application_approved', 'Host Application Approved'), ('host_application_rejected', 'Host Application Rejected'), ('host_application_needs_info', 'Host Application Needs More Info'), ('listing_submitted', 'Listing Submitted'), ('listing_approved', 'Listing Approved'), ('listing_rejected', 'Listing Rejected'), ('listing_suspended', 'Listing Suspended'), ('booking_created', 'Booking Created'), ('booking_confirmed', 'Booking Confirmed'), ('booking_paid', 'Booking Paid'), ('booking_payment_failed', 'Booking Payment Failed'), ('booking_cancelled', 'Booking Cancelled'), ('cash_in_hand_selected', 'Cash In Hand Selected'), ('review_received', 'Review Received'), ('admin_new_host_application', 'Admin New Host Application'), ('admin_host_application_resubmitted', 'Admin Host Application Resubmitted'), ('admin_new_listing_pending', 'Admin New Listing Pending'), ('admin_payment_failed', 'Admin Payment Failed')], max_length=60)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_triggered', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
