# Generated by Django 6.0 on 2026-04-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentit', '0014_notification_rentit_noti_recipie_06d220_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_password_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
