# Generated by Django 6.0 on 2026-04-10 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentit', '0015_user_reset_password_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformsetting',
            name='service_fee_percent',
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='fee_0_to_2000_percent',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='fee_2001_to_6000_percent',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='fee_6001_and_above_percent',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
