"""
Django settings for roamnepalstay project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-+cj7@d206&l5h7yo=yef+8vc_4v#6@#(7a5k=*9kb1+pn^7+rk"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",  # JWT authentication
    "corsheaders",
    "rentit",
]


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOW_ALL_ORIGINS = True


ROOT_URLCONF = "roamnepalstay.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "roamnepalstay.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

# TIME_ZONE = "UTC"

USE_I18N = True

# USE_TZ = True
TIME_ZONE = "Asia/Kathmandu"
USE_TZ = True


# MEDIA_URL = "/media/"
# MEDIA_ROOT = BASE_DIR / "media"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"


AUTH_USER_MODEL = "rentit.User"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "roamnepalstay_db",
        "USER": "postgres",
        "PASSWORD": "Antim",
        "HOST": "localhost",
        "PORT": "5432",
    }
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}

# JWT Settings - JWT token ko configuration
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "UPDATE_LAST_LOGIN": True,
}


# Jazzmin Settings
JAZZMIN_SETTINGS = {
    "site_title": "Roam Nepal Stay Admin",
    "site_header": "Roam Nepal Stay",
    "site_brand": "Roam Nepal Stay",
    "welcome_sign": "Welcome to Roam Nepal Stay Admin",
    "copyright": "Roam Nepal Stay Ltd",
    "search_model": ["rentit.User", "rentit.Listing"],
    "user_avatar": "profile_image",
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "rentit.User"},
        {"app": "rentit"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": [
        "rentit",
        "rentit.User",
        "rentit.Listing",
        "rentit.Booking",
    ],
    "icons": {
        "auth": "fas fa-users-cog",
        "rentit.User": "fas fa-user",
        "rentit.Listing": "fas fa-home",
        "rentit.Booking": "fas fa-calendar-check",
        "rentit.Review": "fas fa-star",
        "rentit.HostApplication": "fas fa-file-contract",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "theme": "flatly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# print("EMAIL_HOST_USER =", EMAIL_HOST_USER)
# print("EMAIL_HOST_PASSWORD =", EMAIL_HOST_PASSWORD)
# print("BASE_DIR =", BASE_DIR)
# print("ENV PATH EXISTS =", (BASE_DIR / ".env").exists())
# print("EMAIL_HOST_USER raw =", os.getenv("EMAIL_HOST_USER"))
# print("EMAIL_HOST_PASSWORD raw =", os.getenv("EMAIL_HOST_PASSWORD"))

# KHALTI_SECRET_KEY = "c831d41cc43f4be088dc047b9f358ae7"
# KHALTI_INITIATE_URL = "https://a.khalti.com/api/v2/epayment/initiate/"
# KHALTI_VERIFY_URL = "https://a.khalti.com/api/v2/epayment/lookup/"
KHALTI_SECRET_KEY = os.getenv("KHALTI_SECRET_KEY", "c831d41cc43f4be088dc047b9f358ae7")
KHALTI_INITIATE_URL = os.getenv(
    "KHALTI_INITIATE_URL",
    "https://dev.khalti.com/api/v2/epayment/initiate/",
)
KHALTI_VERIFY_URL = os.getenv(
    "KHALTI_VERIFY_URL",
    "https://dev.khalti.com/api/v2/epayment/lookup/",
)
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:5173")

FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:5173")

# KHALTI_SECRET_KEY = os.getenv("KHALTI_SECRET_KEY", "")
# KHALTI_INITIATE_URL = "https://a.khalti.com/api/v2/epayment/initiate/"
# KHALTI_VERIFY_URL = "https://a.khalti.com/api/v2/epayment/lookup/"

ESEWA_PRODUCT_CODE = os.getenv("ESEWA_PRODUCT_CODE", "EPAYTEST")
ESEWA_SECRET_KEY = os.getenv("ESEWA_SECRET_KEY", "8gBm/:&EnhH.1/q")
ESEWA_FORM_URL = os.getenv(
    "ESEWA_FORM_URL", "https://rc-epay.esewa.com.np/api/epay/main/v2/form"
)
ESEWA_STATUS_CHECK_URL = os.getenv(
    "ESEWA_STATUS_CHECK_URL",
    "https://rc.esewa.com.np/api/epay/transaction/status/",
)
